language: node_js

node_js:
  - '14'
  - '16'

os:
  - linux

cache: yarn

before_install:
  # https://code.visualstudio.com/api/working-with-extensions/continuous-integration#travis
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
  - yarn

notifications:
  email: false
