name: Main

on: push

jobs:
  lint:
    name: Lint
    if: ${{ !startsWith(github.ref, 'refs/heads/ci-release-v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
      - name: Install
        run: yarn
      - name: Lint commits
        uses: wagoid/commitlint-github-action@v5
        with:
          commitDepth: 25
          configFile: ./.commitlintrc
          failOnWarnings: true
      - name: Lint code
        run: yarn test:lint

  type:
    name: Type
    if: ${{ !startsWith(github.ref, 'refs/heads/ci-release-v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
      - name: Install
        run: yarn
      - name: Type
        run: yarn test:type

  # test:
  #   name: Test
  #   if: ${{ !startsWith(github.head_ref, 'ci-release-v') }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         cache: yarn
  #         node-version: 18
  #     - name: Install
  #       run: yarn
  #     - name: Test
  #       run: yarn test:unit

  # release:
  #   name: Release
  #   if: ${{ !startsWith(github.head_ref, 'ci-release-v') && github.ref == 'refs/heads/main' }}
  #   needs: [lint, type, test, dist]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #         persist-credentials: false
  #     - name: Download binaries
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: binaries
  #         path: ./dist
  #     - name: Setup
  #       uses: actions/setup-node@v3
  #       with:
  #         cache: yarn
  #         node-version: 18
  #     - name: Install
  #       run: yarn install --frozen-lockfile
  #     - name: Release
  #       run: yarn release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  #     - name: Get version
  #       id: get_version
  #       run: echo ::set-output name=version::$(npm pkg get version | sed 's/"//g')
  #     - name: Create pull request
  #       uses: peter-evans/create-pull-request@v4
  #       with:
  #         branch: ci-release-v${{ steps.get_version.outputs.version }}
  #         # https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
  #         commit-message: 'ci(release): ${{ steps.get_version.outputs.version }}'
  #         title: 'ci(release): ${{ steps.get_version.outputs.version }}'
  #         token: ${{ secrets.GH_PAT }}
