name: Releases

on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 20
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - name: Get version
        id: get_version
        run: echo ::set-output name=version::$(npm pkg get version | sed 's/"//g')
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: ci-release-v${{ steps.get_version.outputs.version }}
          # https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
          commit-message: 'ci(release): ${{ steps.get_version.outputs.version }}'
          title: 'ci(release): ${{ steps.get_version.outputs.version }}'
          token: ${{ secrets.GH_PAT }}
